# Security: Require packages to be at least 7 days old before installation
# This reduces the risk of supply chain attacks by delaying installation of newly published versions
minimumReleaseAge: 10080
