// Interface automatically generated by schemas-to-ts

export interface Calendrier {
  date: string;
  titre: string;
  description?: any;
}
export interface Calendrier_Plain {
  date: string;
  titre: string;
  description?: any;
}

export interface Calendrier_NoRelations {
  date: string;
  titre: string;
  description?: any;
}

