// Interface automatically generated by schemas-to-ts

import { Media } from '../../common/Media';
import { Media_Plain } from '../../common/Media';

export interface Situation {
  image?: { data: Media };
  description: any;
}
export interface Situation_Plain {
  image?: Media_Plain;
  description: any;
}

export interface Situation_NoRelations {
  image?: number;
  description: any;
}

