// Interface automatically generated by schemas-to-ts, adapted for Strapi v5's flat GraphQL response

import { Media } from "../../common/Media";

export interface Situation {
  image?: Media;
  description: any;
}
