// Interface automatically generated by schemas-to-ts

export interface EtapeEntretien {
  titre: string;
  description: any;
}
export interface EtapeEntretien_Plain {
  titre: string;
  description: any;
}

export interface EtapeEntretien_NoRelations {
  titre: string;
  description: any;
}

