// Interface automatically generated by schemas-to-ts

export interface EtapeDiagnostic {
  titre: string;
  description: any;
}
export interface EtapeDiagnostic_Plain {
  titre: string;
  description: any;
}

export interface EtapeDiagnostic_NoRelations {
  titre: string;
  description: any;
}

