// Interface automatically generated by schemas-to-ts

export interface EtapeMiseEnOeuvre {
  titre: string;
  description: any;
}
export interface EtapeMiseEnOeuvre_Plain {
  titre: string;
  description: any;
}

export interface EtapeMiseEnOeuvre_NoRelations {
  titre: string;
  description: any;
}

