// Interface automatically generated by schemas-to-ts, adapted for Strapi v5's flat GraphQL response

import { FicheSolution } from "../../api/fiche-solution";

export interface Oups {
  description: any;
  titre: string;
  solutions_reparatrices: FicheSolution[];
}
