// Interface automatically generated by schemas-to-ts

import { FicheSolution } from '../../api/fiche-solution';
import { FicheSolution_Plain } from '../../api/fiche-solution';

export interface Oups {
  description: any;
  titre: string;
  solutions_reparatrices: { data: FicheSolution[] };
}
export interface Oups_Plain {
  description: any;
  titre: string;
  solutions_reparatrices: FicheSolution_Plain[];
}

export interface Oups_NoRelations {
  description: any;
  titre: string;
  solutions_reparatrices: number[];
}

