// Interface automatically generated by schemas-to-ts

export interface UtiliteMethode {
  description: string;
}
export interface UtiliteMethode_Plain {
  description: string;
}

export interface UtiliteMethode_NoRelations {
  description: string;
}

