// Interface automatically generated by schemas-to-ts

export interface Citation {
  auteur: string;
  texte: any;
}
export interface Citation_Plain {
  auteur: string;
  texte: any;
}

export interface Citation_NoRelations {
  auteur: string;
  texte: any;
}

