// Interface automatically generated by schemas-to-ts

import { Media } from '../../common/Media';
import { Media_Plain } from '../../common/Media';

export interface ImageWithCaption {
  caption?: string;
  image: { data: Media };
}
export interface ImageWithCaption_Plain {
  caption?: string;
  image: Media_Plain;
}

export interface ImageWithCaption_NoRelations {
  caption?: string;
  image: number;
}

