// Interface automatically generated by schemas-to-ts, adapted for Strapi v5's flat GraphQL response

import { Media } from "../common/Media";
import { FicheSolution } from "./fiche-solution";

export interface AideDecisionEtape {
  documentId: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  nom: string;
  description?: string;
  question_suivante?: string;
  image?: Media;
  slug: string;
  fiches_solutions: FicheSolution[];
  etapes_suivantes: AideDecisionEtape[];
  etape_precedente?: AideDecisionEtape;
  rank?: number;
}
