// Interface automatically generated by schemas-to-ts

import { Media } from '../common/Media';
import { FicheSolution } from './fiche-solution';
import { Media_Plain } from '../common/Media';
import { FicheSolution_Plain } from './fiche-solution';
import { AdminPanelRelationPropertyModification } from '../common/AdminPanelRelationPropertyModification';

export interface AideDecisionEtape {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    nom: string;
    description?: string;
    question_suivante?: string;
    image?: { data: Media };
    slug: string;
    fiches_solutions: { data: FicheSolution[] };
    etapes_suivantes: { data: AideDecisionEtape[] };
    etape_precedente?: { data: AideDecisionEtape };
    rank?: number;
  };
}
export interface AideDecisionEtape_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  nom: string;
  description?: string;
  question_suivante?: string;
  image?: Media_Plain;
  slug: string;
  fiches_solutions: FicheSolution_Plain[];
  etapes_suivantes: AideDecisionEtape_Plain[];
  etape_precedente?: AideDecisionEtape_Plain;
  rank?: number;
}

export interface AideDecisionEtape_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  nom: string;
  description?: string;
  question_suivante?: string;
  image?: number;
  slug: string;
  fiches_solutions: number[];
  etapes_suivantes: number[];
  etape_precedente?: number;
  rank?: number;
}

export interface AideDecisionEtape_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  nom: string;
  description?: string;
  question_suivante?: string;
  image?: AdminPanelRelationPropertyModification<Media_Plain>;
  slug: string;
  fiches_solutions: AdminPanelRelationPropertyModification<FicheSolution_Plain>;
  etapes_suivantes: AdminPanelRelationPropertyModification<AideDecisionEtape_Plain>;
  etape_precedente?: AdminPanelRelationPropertyModification<AideDecisionEtape_Plain>;
  rank?: number;
}
