// Interface automatically generated by schemas-to-ts

import { FicheSolution } from './fiche-solution';
import { FicheSolution_Plain } from './fiche-solution';
import { AdminPanelRelationPropertyModification } from '../common/AdminPanelRelationPropertyModification';

export enum Icone {
  AbriterBiodiversite = 'abriter_biodiversite',
  AmeliorerBienEtreSante = 'ameliorer_bien_etre_sante',
  AmeliorerQualiteAir = 'ameliorer_qualite_air',
  CreerLienSocial = 'creer_lien_social',
  FaireEconomiesEauPotable = 'faire_economies_eau_potable',
  FiltrerPollutionsPreserverQualiteEaux = 'filtrer_pollutions_preserver_qualite_eaux',
  GererEauxPluviales = 'gerer_eaux_pluviales',
  PrevenirRisquesInnondation = 'prevenir_risques_innondation',
  ProlongeeDurabiliteEquipement = 'prolongee_durabilite_equipement',
  ReduidePlaceVoitureEnVille = 'reduide_place_voiture_en_ville',
  ReduireConsommationsEnergetiques = 'reduire_consommations_energetiques',
  ReduireNuisancesSonores = 'reduire_nuisances_sonores',
  RendreEspacesPublicsPlusAccueillants = 'rendre_espaces_publics_plus_accueillants',
  RendreVillePlusLudique = 'rendre_ville_plus_ludique',
  SensibiliserVivantNature = 'sensibiliser_vivant_nature',
  SequestrerDuCarbone = 'sequestrer_du_carbone',}

export interface Cobenefice {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    description: string;
    icone?: Icone;
    fiches_solutions?: { data: FicheSolution[] };
  };
}
export interface Cobenefice_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  description: string;
  icone?: Icone;
  fiches_solutions?: FicheSolution_Plain[];
}

export interface Cobenefice_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  description: string;
  icone?: Icone;
  fiches_solutions?: number[];
}

export interface Cobenefice_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  description: string;
  icone?: Icone;
  fiches_solutions?: AdminPanelRelationPropertyModification<FicheSolution_Plain>;
}
