// Interface automatically generated by schemas-to-ts, adapted for Strapi v5's flat GraphQL response

import { FicheSolution } from "./fiche-solution";

export enum Icone {
  AbriterBiodiversite = "abriter_biodiversite",
  AmeliorerBienEtreSante = "ameliorer_bien_etre_sante",
  AmeliorerQualiteAir = "ameliorer_qualite_air",
  CreerLienSocial = "creer_lien_social",
  FaireEconomiesEauPotable = "faire_economies_eau_potable",
  FiltrerPollutionsPreserverQualiteEaux = "filtrer_pollutions_preserver_qualite_eaux",
  GererEauxPluviales = "gerer_eaux_pluviales",
  PrevenirRisquesInnondation = "prevenir_risques_innondation",
  ProlongeeDurabiliteEquipement = "prolongee_durabilite_equipement",
  ReduidePlaceVoitureEnVille = "reduide_place_voiture_en_ville",
  ReduireConsommationsEnergetiques = "reduire_consommations_energetiques",
  ReduireNuisancesSonores = "reduire_nuisances_sonores",
  RendreEspacesPublicsPlusAccueillants = "rendre_espaces_publics_plus_accueillants",
  RendreVillePlusLudique = "rendre_ville_plus_ludique",
  SensibiliserVivantNature = "sensibiliser_vivant_nature",
  SequestrerDuCarbone = "sequestrer_du_carbone",
}

export interface Cobenefice {
  documentId: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  description: string;
  icone?: Icone;
  fiches_solutions?: FicheSolution[];
}
