// Interface automatically generated by schemas-to-ts, adapted for Strapi v5's flat GraphQL response

import { EtapeMiseEnOeuvre } from "../components/fiche-diagnostic/EtapeMiseEnOeuvre";
import { Media } from "../common/Media";
import { UtiliteMethode } from "../components/fiche-diagnostic/UtiliteMethode";
import { LienRexDiagnostic } from "./lien-rex-diagnostic";

export enum Echelle {
  Territoire = "territoire",
  Espace = "espace",
}

export enum Methode {
  Observation = "observation",
  Enquete = "enquete",
  SimulationNumerique = "simulation_numerique",
  AnalyseSpatiale = "analyse_spatiale",
  ModelisationSpatiale = "modelisation_spatiale",
}

export interface FicheDiagnostic {
  documentId: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  titre: string;
  description_courte: string;
  description: any;
  etapes_mise_en_oeuvre: EtapeMiseEnOeuvre[];
  rank?: number;
  image_principale?: Media;
  echelle?: Echelle;
  methode?: Methode;
  slug: string;
  besoin?: any;
  indicateurs?: any;
  delai_min?: number;
  delai_max?: number;
  cout_min?: number;
  cout_max?: number;
  explication_source?: string;
  avantage_description: any;
  vigilance_description: any;
  en_savoir_plus_description?: any;
  fiches_diagnostics_associees: FicheDiagnostic[];
  materiel?: any;
  partenaire?: any;
  objectifs: UtiliteMethode[];
  explication_cout?: string;
  nom_scientifique?: string;
  type_livrables?: string;
  echelle_thermique?: any;
  echelle_spatiale?: any;
  lien_rex_diagnostics: LienRexDiagnostic[];
  image_icone?: Media;
}
