// Interface automatically generated by schemas-to-ts

import { EtapeMiseEnOeuvre } from "../components/fiche-diagnostic/EtapeMiseEnOeuvre";
import { Media } from "../common/Media";
import { UtiliteMethode } from "../components/fiche-diagnostic/UtiliteMethode";
import { LienRexDiagnostic } from "./lien-rex-diagnostic";
import { EtapeMiseEnOeuvre_Plain } from "../components/fiche-diagnostic/EtapeMiseEnOeuvre";
import { Media_Plain } from "../common/Media";
import { UtiliteMethode_Plain } from "../components/fiche-diagnostic/UtiliteMethode";
import { LienRexDiagnostic_Plain } from "./lien-rex-diagnostic";
import { EtapeMiseEnOeuvre_NoRelations } from "../components/fiche-diagnostic/EtapeMiseEnOeuvre";
import { UtiliteMethode_NoRelations } from "../components/fiche-diagnostic/UtiliteMethode";
import { AdminPanelRelationPropertyModification } from "../common/AdminPanelRelationPropertyModification";

export enum Echelle {
  Territoire = "territoire",
  Espace = "espace",
}
export enum Methode {
  Observation = "observation",
  Enquete = "enquete",
  SimulationNumerique = "simulation_numerique",
  AnalyseSpatiale = "analyse_spatiale",
  ModelisationSpatiale = "modelisation_spatiale",
}

export interface FicheDiagnostic {
  id: number;
  attributes: {
    createdAt: Date;
    updatedAt: Date;
    publishedAt?: Date;
    titre: string;
    description_courte: string;
    description: any;
    etapes_mise_en_oeuvre: EtapeMiseEnOeuvre[];
    rank?: number;
    image_principale?: { data: Media };
    echelle?: Echelle;
    methode?: Methode;
    slug: string;
    besoin?: any;
    indicateurs?: any;
    delai_min?: number;
    delai_max?: number;
    cout_min?: number;
    cout_max?: number;
    explication_source?: string;
    avantage_description: any;
    vigilance_description: any;
    en_savoir_plus_description?: any;
    fiches_diagnostics_associees: { data: FicheDiagnostic[] };
    materiel?: any;
    partenaire?: any;
    utilite_methode: UtiliteMethode[];
    explication_cout?: string;
    nom_scientifique?: string;
    type_livrables?: string;
    effets_attendus?: any;
    echelle_spatiale?: any;
    lien_rex_diagnostics: { data: LienRexDiagnostic[] };
    image_icone?: { data: Media };
  };
}
export interface FicheDiagnostic_Plain {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  titre: string;
  description_courte: string;
  description: any;
  etapes_mise_en_oeuvre: EtapeMiseEnOeuvre_Plain[];
  rank?: number;
  image_principale?: Media_Plain;
  echelle?: Echelle;
  methode?: Methode;
  slug: string;
  besoin?: any;
  indicateurs?: any;
  delai_min?: number;
  delai_max?: number;
  cout_min?: number;
  cout_max?: number;
  explication_source?: string;
  avantage_description: any;
  vigilance_description: any;
  en_savoir_plus_description?: any;
  fiches_diagnostics_associees: FicheDiagnostic_Plain[];
  materiel?: any;
  partenaire?: any;
  utilite_methode: UtiliteMethode_Plain[];
  explication_cout?: string;
  nom_scientifique?: string;
  type_livrables?: string;
  effets_attendus?: any;
  echelle_spatiale?: any;
  lien_rex_diagnostics: LienRexDiagnostic_Plain[];
  image_icone?: Media_Plain;
}

export interface FicheDiagnostic_NoRelations {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  titre: string;
  description_courte: string;
  description: any;
  etapes_mise_en_oeuvre: EtapeMiseEnOeuvre_NoRelations[];
  rank?: number;
  image_principale?: number;
  echelle?: Echelle;
  methode?: Methode;
  slug: string;
  besoin?: any;
  indicateurs?: any;
  delai_min?: number;
  delai_max?: number;
  cout_min?: number;
  cout_max?: number;
  explication_source?: string;
  avantage_description: any;
  vigilance_description: any;
  en_savoir_plus_description?: any;
  fiches_diagnostics_associees: number[];
  materiel?: any;
  partenaire?: any;
  utilite_methode: UtiliteMethode_NoRelations[];
  explication_cout?: string;
  nom_scientifique?: string;
  type_livrables?: string;
  effets_attendus?: any;
  echelle_spatiale?: any;
  lien_rex_diagnostics: number[];
  image_icone?: number;
}

export interface FicheDiagnostic_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  titre: string;
  description_courte: string;
  description: any;
  etapes_mise_en_oeuvre: EtapeMiseEnOeuvre_Plain[];
  rank?: number;
  image_principale?: AdminPanelRelationPropertyModification<Media_Plain>;
  echelle?: Echelle;
  methode?: Methode;
  slug: string;
  besoin?: any;
  indicateurs?: any;
  delai_min?: number;
  delai_max?: number;
  cout_min?: number;
  cout_max?: number;
  explication_source?: string;
  avantage_description: any;
  vigilance_description: any;
  en_savoir_plus_description?: any;
  fiches_diagnostics_associees: AdminPanelRelationPropertyModification<FicheDiagnostic_Plain>;
  materiel?: any;
  partenaire?: any;
  utilite_methode: UtiliteMethode_Plain[];
  explication_cout?: string;
  nom_scientifique?: string;
  type_livrables?: string;
  effets_attendus?: any;
  echelle_spatiale?: any;
  lien_rex_diagnostics: AdminPanelRelationPropertyModification<LienRexDiagnostic_Plain>;
  image_icone?: AdminPanelRelationPropertyModification<Media_Plain>;
}
