// Interface automatically generated by schemas-to-ts, adapted for Strapi v5's flat GraphQL response

import { Media } from "../common/Media";
import { SolutionRetourExperience } from "./solution-retour-experience";
import { EtapeMiseEnOeuvre } from "../components/fiche-diagnostic/EtapeMiseEnOeuvre";
import { EtapeEntretien } from "../components/fiche-solution/EtapeEntretien";
import { EtapeDiagnostic } from "../components/fiche-solution/EtapeDiagnostic";
import { Materiau } from "./materiau";
import { Cobenefice } from "./cobenefice";
import { Oups } from "../components/fiche-solution/Oups";

export enum TypeSolution {
  Bleue = "bleue",
  Verte = "verte",
  Grise = "grise",
  Douce = "douce",
}
export enum PorteeBaisseTemperature {
  Air = "air",
  Surface = "surface",
  Interieur = "interieur",
}
export enum CoutEntretienUnite {
  MetreCarre = "metreCarre",
  Lineaire = "lineaire",
  MetreCube = "metreCube",
  Unite = "unite",
  MegaWattHeure = "megaWattHeure",
  KiloWatt = "kiloWatt",
}
export enum CoutUnite {
  MetreCarre = "metreCarre",
  MegaWattHeure = "megaWattHeure",
}

export interface FicheSolution {
  documentId: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  titre: string;
  slug: string;
  image_principale?: Media;
  solution_retour_experiences: SolutionRetourExperience[];
  cout_minimum?: number;
  cout_maximum?: number;
  type_solution?: TypeSolution;
  description_courte: string;
  description: any;
  baisse_temperature?: number;
  contexte_titre: string;
  contexte_description: any;
  rafraichissement_attendu_description?: any;
  logo_partenaire?: Media;
  cout_minimum_entretien?: number;
  cout_maximum_entretien?: number;
  etapes_mise_en_oeuvre: EtapeMiseEnOeuvre[];
  etapes_entretien: EtapeEntretien[];
  point_vigilance?: any;
  lien_fond_vert?: string;
  types_espace?: any;
  etapes_diagnostic: EtapeDiagnostic[];
  rank?: number;
  materiaux?: Materiau[];
  fiches_solutions_complementaires: FicheSolution[];
  cobenefices?: Cobenefice[];
  oups: Oups[];
  cout_entretien_description?: any;
  delai_travaux_minimum?: number;
  delai_travaux_maximum?: number;
  portee_baisse_temperature?: PorteeBaisseTemperature;
  cout_entretien_unite?: CoutEntretienUnite;
  en_savoir_plus?: any;
  libelle_avantage_solution?: string;
  credits?: any;
  cout_unite?: CoutUnite;
  description_estimation?: any;
  aides_territoires_mots_cles?: string;
}
