// Interface automatically generated by schemas-to-ts, adapted for Strapi v5's flat GraphQL response

import { FicheDiagnostic } from "./fiche-diagnostic";
import { RetourExperienceDiagnostic } from "./retour-experience-diagnostic";

export interface LienRexDiagnostic {
  documentId: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  fiche_diagnostic?: FicheDiagnostic;
  retour_experience_diagnostic?: RetourExperienceDiagnostic;
  description?: any;
}
