// Interface automatically generated by schemas-to-ts, adapted for Strapi v5's flat GraphQL response

import { Media } from "../common/Media";
import { FicheSolution } from "./fiche-solution";

export enum CoutUnite {
  MetreCarre = "metreCarre",
  Lineaire = "lineaire",
  MetreCube = "metreCube",
  Unite = "unite",
  MegaWattHeure = "megaWattHeure",
  KiloWatt = "kiloWatt",
}

export interface Materiau {
  documentId: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  titre: string;
  image?: Media;
  description: any;
  cout_minimum_fourniture?: number;
  cout_maximum_fourniture?: number;
  cout_minimum_entretien?: number;
  cout_maximum_entretien?: number;
  cout_unite: CoutUnite;
  fiches_solution?: FicheSolution[];
}
