// Interface automatically generated by schemas-to-ts

export interface ObjectifDeveloppementDurable {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    numero: number;
    description: string;
  };
}
export interface ObjectifDeveloppementDurable_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  numero: number;
  description: string;
}

export interface ObjectifDeveloppementDurable_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  numero: number;
  description: string;
}

export interface ObjectifDeveloppementDurable_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  numero: number;
  description: string;
}
