// Interface automatically generated by schemas-to-ts, adapted for Strapi v5's flat GraphQL response

export interface Region {
  documentId: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  code: string;
  nom?: string;
}
