// Interface automatically generated by schemas-to-ts

export interface Region {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    code: string;
    nom?: string;
  };
}
export interface Region_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  code: string;
  nom?: string;
}

export interface Region_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  code: string;
  nom?: string;
}

export interface Region_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  code: string;
  nom?: string;
}
