// Interface automatically generated by schemas-to-ts, adapted for Strapi v5's flat GraphQL response

import { Media } from "../common/Media";
import { Citation } from "../components/common/Citation";
import { LienRexDiagnostic } from "./lien-rex-diagnostic";
import { Contact } from "../components/retour-experience/Contact";
import { ImageWithCaption } from "../components/common/ImageWithCaption";

export interface RetourExperienceDiagnostic {
  documentId: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  image_principale?: Media;
  titre: string;
  lieu: string;
  description: any;
  citations: Citation[];
  collectivite_info?: any;
  climat_actuel?: string;
  climat_futur?: string;
  annee_realisation?: string;
  cout_description?: any;
  financements?: any;
  besoin?: any;
  resultats?: any;
  points_vigilance?: any;
  apres?: any;
  lien_rex_diagnostics: LienRexDiagnostic[];
  slug: string;
  contacts: Contact[];
  credits?: any;
  guide_pdf?: Media;
  resultats_images: ImageWithCaption[];
}
