// Interface automatically generated by schemas-to-ts, adapted for Strapi v5's flat GraphQL response

import { Media } from "../common/Media";
import { Citation } from "../components/common/Citation";
import { Region } from "./region";
import { ObjectifDeveloppementDurable } from "./objectif-developpement-durable";
import { Situation } from "../components/retour-experience/Situation";
import { Calendrier } from "../components/retour-experience/Calendrier";
import { SolutionRetourExperience } from "./solution-retour-experience";
import { Contact } from "../components/retour-experience/Contact";

export enum ClimatActuel {
  Oceanique = "oceanique",
  Mediterraneen = "mediterraneen",
  SemiAride = "semi_aride",
  SemiContinental = "semi_continental",
  Equatorial = "equatorial",
  Tempere = "tempere",
  Tropical = "tropical",
}
export enum ClimatFutur {
  Oceanique = "oceanique",
  Mediterraneen = "mediterraneen",
  SemiAride = "semi_aride",
  SemiContinental = "semi_continental",
  Equatorial = "equatorial",
  Tempere = "tempere",
  Tropical = "tropical",
}
export enum Temporalite {
  CourtTerme = "court_terme",
  MoyenTerme = "moyen_terme",
  LongTerme = "long_terme",
}

export interface RetourExperience {
  documentId: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  titre: string;
  slug: string;
  image_principale?: Media;
  types_solutions?: any;
  citations: Citation[];
  region?: Region;
  climat_actuel?: ClimatActuel;
  climat_futur?: ClimatFutur;
  echelle?: string;
  temporalite?: Temporalite;
  cout?: string;
  types_espaces?: any;
  retour_experiences: RetourExperience[];
  odds: ObjectifDeveloppementDurable[];
  situation_avant?: Situation;
  situation_apres?: Situation;
  calendrier: Calendrier[];
  solution_retour_experiences: SolutionRetourExperience[];
  description: any;
  porteur?: any;
  contact?: any;
  financement?: any;
  difficultes?: any;
  partenaires?: any;
  ressources?: any;
  credits?: any;
  rank?: number;
  location?: any;
  contacts: Contact[];
  cout_euro?: number;
  export_aquagir?: boolean;
}
