// Interface automatically generated by schemas-to-ts

import { Media } from "../common/Media";
import { Citation } from "../components/common/Citation";

import { Contact } from "../components/retour-experience/Contact";
import { ImageWithCaption } from "../components/common/ImageWithCaption";
import { Media_Plain } from "../common/Media";
import { Citation_Plain } from "../components/common/Citation";

import { Contact_Plain } from "../components/retour-experience/Contact";
import { ImageWithCaption_Plain } from "../components/common/ImageWithCaption";
import { Citation_NoRelations } from "../components/common/Citation";
import { Contact_NoRelations } from "../components/retour-experience/Contact";
import { ImageWithCaption_NoRelations } from "../components/common/ImageWithCaption";
import { AdminPanelRelationPropertyModification } from "../common/AdminPanelRelationPropertyModification";
import { LienRexDiagnostic, LienRexDiagnostic_Plain } from "./lien-rex-diagnostic";

export interface RetourExperienceDiagnostic {
  id: number;
  attributes: {
    createdAt: Date;
    updatedAt: Date;
    publishedAt?: Date;
    image_principale?: { data: Media };
    titre: string;
    lieu: string;
    description: any;
    citations: Citation[];
    collectivite_info?: any;
    climat_actuel?: string;
    climat_futur?: string;
    annee_realisation?: string;
    cout_description?: any;
    financements?: any;
    besoin?: any;
    resultats?: any;
    points_vigilance?: any;
    apres?: any;
    partenaires?: any;
    lien_rex_diagnostics: { data: LienRexDiagnostic[] };
    slug: string;
    contacts: Contact[];
    credits?: any;
    guide_pdf?: { data: Media };
    resultats_images: ImageWithCaption[];
  };
}
export interface RetourExperienceDiagnostic_Plain {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  image_principale?: Media_Plain;
  titre: string;
  lieu: string;
  description: any;
  citations: Citation_Plain[];
  collectivite_info?: any;
  climat_actuel?: string;
  climat_futur?: string;
  annee_realisation?: string;
  cout_description?: any;
  financements?: any;
  besoin?: any;
  resultats?: any;
  points_vigilance?: any;
  apres?: any;
  partenaires?: any;
  lien_rex_diagnostics: LienRexDiagnostic_Plain[];
  slug: string;
  contacts: Contact_Plain[];
  credits?: any;
  guide_pdf?: Media_Plain;
  resultats_images: ImageWithCaption_Plain[];
}

export interface RetourExperienceDiagnostic_NoRelations {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  image_principale?: number;
  titre: string;
  lieu: string;
  description: any;
  citations: Citation_NoRelations[];
  collectivite_info?: any;
  climat_actuel?: string;
  climat_futur?: string;
  annee_realisation?: string;
  cout_description?: any;
  financements?: any;
  besoin?: any;
  resultats?: any;
  points_vigilance?: any;
  apres?: any;
  partenaires?: any;
  lien_rex_diagnostics: number[];
  slug: string;
  contacts: Contact_NoRelations[];
  credits?: any;
  guide_pdf?: number;
  resultats_images: ImageWithCaption_NoRelations[];
}

export interface RetourExperienceDiagnostic_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  image_principale?: AdminPanelRelationPropertyModification<Media_Plain>;
  titre: string;
  lieu: string;
  description: any;
  citations: Citation_Plain[];
  collectivite_info?: any;
  climat_actuel?: string;
  climat_futur?: string;
  annee_realisation?: string;
  cout_description?: any;
  financements?: any;
  besoin?: any;
  resultats?: any;
  points_vigilance?: any;
  apres?: any;
  partenaires?: any;
  lien_rex_diagnostics: AdminPanelRelationPropertyModification<LienRexDiagnostic_Plain>;
  slug: string;
  contacts: Contact_Plain[];
  credits?: any;
  guide_pdf?: AdminPanelRelationPropertyModification<Media_Plain>;
  resultats_images: ImageWithCaption_Plain[];
}
