// Interface automatically generated by schemas-to-ts, adapted for Strapi v5's flat GraphQL response

import { Media } from "../common/Media";
import { FicheSolution } from "./fiche-solution";
import { RetourExperience } from "./retour-experience";

export interface SolutionRetourExperience {
  documentId: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  titre: string;
  image?: Media;
  fiche_solution?: FicheSolution;
  retour_experience?: RetourExperience;
  description?: any;
}
