// Interface automatically generated by schemas-to-ts, adapted for Strapi v5's flat GraphQL response

export interface Webinaire {
  documentId: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  titre?: string;
  description?: any;
  lien_inscription?: string;
  lien_replay?: string;
  jour_evenement?: Date;
  heure_debut?: Date;
  heure_fin?: Date;
  lien_btn_secondaire?: string;
  label_btn_secondaire?: string;
}
