// Interface automatically generated by schemas-to-ts

export interface Webinaire {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    titre?: string;
    description?: any;
    lien_inscription?: string;
    lien_replay?: string;
    jour_evenement?: Date;
    heure_debut?: Date;
    heure_fin?: Date;
  };
}
export interface Webinaire_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  titre?: string;
  description?: any;
  lien_inscription?: string;
  lien_replay?: string;
  jour_evenement?: Date;
  heure_debut?: Date;
  heure_fin?: Date;
}

export interface Webinaire_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  titre?: string;
  description?: any;
  lien_inscription?: string;
  lien_replay?: string;
  jour_evenement?: Date;
  heure_debut?: Date;
  heure_fin?: Date;
}

export interface Webinaire_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  titre?: string;
  description?: any;
  lien_inscription?: string;
  lien_replay?: string;
  jour_evenement?: Date;
  heure_debut?: Date;
  heure_fin?: Date;
}
